AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation demo template
Resources:
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: tech-ex-demo-bucket-211026-test # unique bucket name goes here test